export { default as SignUp} from './SignUp'
export { default as SignIn} from './SignIn'
export { default as Home } from './Home'
export { default as ProfileSetup } from './ProfileSetup'
export { default as Error } from './Error'