import { Form } from 'react-router-dom'

export { default as SignUp} from './auth/SignUp'
export { default as SignIn} from './auth/SignIn'
export { default as ProfileSetup } from './profile/ProfileSetup'
export { default as HomeMap } from './MapComponents/HomeMap'
export { default as Error } from './support/Error'
export { default as Resetpassword }from './auth/Resetpassword'
export { default as Help } from './support/Help'
export { default as Suggestions } from './support/Suggestions'
export { default as About } from './support/About'
export { default as Footer } from './homepage/Footer'
export { default as Profile } from './profile/Profile'
export { default as EditProfile } from './profile/EditProfile'
export { default as CreateEventMap } from './MapComponents/CreateEventMap'
export { default as FriendsList } from './profile/FriendsList'
export { default as CreateEventForm } from './MapComponents/CreateEventForm'
export {default as EventList} from './Events/EventList'
export {default as SingleEventView} from './Events/SingleEventView'
export {default as EventsListFiltered } from './Events/AttendanceEventsList'
export { default as Toggle } from './toggle/Toggle'
export { default as EditEvent } from './Events/EditEvent'
export { default as OneEventInList } from './Events/OneEventInList'
