export { default as SignUp} from './SignUp'
export { default as SignIn} from './SignIn'
export { default as Home } from './Home'
export { default as ProfileSetup } from './ProfileSetup'
export { default as Error } from './Error'
export { default as Resetpassword }from './Resetpassword'
export { default as Settings } from './Settings'
export { default as Navbar } from './Navbar'
export { default as Help } from './Help'
export { default as Suggestions } from './Suggestions'
export { default as About } from './About'